import type { Property } from './types';

export const properties: Property[] = [
  {
    id: 'prop1',
    title: 'Modern Downtown Loft',
    address: '123 Main St, Anytown, USA',
    price: 2500,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1200,
    description: 'Stunning modern loft in the heart of downtown. Features high ceilings, large windows, and a gourmet kitchen. Perfect for urban living.',
    amenities: ['Gym', 'Rooftop Deck', 'In-unit Laundry', 'Parking'],
    imageIds: ['prop1-1', 'prop1-2', 'prop1-3'],
    owner: {
      name: 'Jane Doe',
      avatarId: 'avatar-1',
    },
  },
  {
    id: 'prop2',
    title: 'Cozy Suburban Family Home',
    address: '456 Oak Ave, Suburbia, USA',
    price: 3200,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2400,
    description: 'Charming and spacious family home in a quiet suburban neighborhood. Large backyard, great schools, and close to parks.',
    amenities: ['Large Backyard', 'Garage', 'Fireplace', 'Pet Friendly'],
    imageIds: ['prop2-1', 'prop2-2', 'prop2-3'],
    owner: {
      name: 'John Smith',
      avatarId: 'avatar-2',
    },
  },
  {
    id: 'prop3',
    title: 'Rustic Getaway Cabin',
    address: '789 Pine Rd, Mountains, USA',
    price: 1500,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 800,
    description: 'Escape to this beautiful rustic cabin. Enjoy peace and quiet, surrounded by nature. Ideal for weekend getaways or a solo retreat.',
    amenities: ['Wood Stove', 'Hiking Trails', 'Deck', 'Secluded'],
    imageIds: ['prop3-1', 'prop3-2'],
    owner: {
      name: 'Emily White',
      avatarId: 'avatar-3',
    },
  },
  {
    id: 'prop4',
    title: 'Affordable Studio Apartment',
    address: '101 University Dr, Collegetown, USA',
    price: 950,
    bedrooms: 0,
    bathrooms: 1,
    sqft: 450,
    description: 'Compact and convenient studio apartment, perfect for students or young professionals. All utilities included.',
    amenities: ['Utilities Included', 'On-site Laundry', 'Near Public Transit'],
    imageIds: ['prop4-1', 'prop4-2'],
    owner: {
      name: 'Michael Brown',
      avatarId: 'avatar-4',
    },
  },
    {
    id: 'prop5',
    title: 'Luxury Penthouse Suite',
    address: '999 Skyline Blvd, Metropolis, USA',
    price: 7500,
    bedrooms: 3,
    bathrooms: 4,
    sqft: 3500,
    description: 'Experience the height of luxury in this stunning penthouse. Breathtaking panoramic city views, private rooftop terrace, and world-class amenities.',
    amenities: ['Private Elevator', 'Concierge', 'Pool', 'Home Theater'],
    imageIds: ['prop5-1', 'prop5-2', 'prop5-3'],
    owner: {
      name: 'Jane Doe',
      avatarId: 'avatar-1',
    },
  },
];
